services:
  dapr-placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006", "-metadata-enabled", "true"]
    ports:
      - "50006:50006"
      - "8082:8080"
      - "8083:9090"
  
  dapr-scheduler:
    image: "daprio/dapr"
    command: ["./scheduler", "--port", "50007", "--etcd-data-dir=/var/lock/dapr/scheduler"]
    ports:
      - "50007:50007"
    volumes:
    - type: tmpfs
      target: /data
      tmpfs:
        size: "10000"

  redis:
    image: "redis"
    hostname: redis-service
    ports:
      - "6379:6379"

  zipkin:
    image: "openzipkin/zipkin-slim:latest"
    ports:
      - "9411:9411"

  dapr-dashboard:
    image: "daprio/dashboard:latest"
    command: [ "--docker-compose=true", 
      "--components-path=/home/nonroot/components", 
      "--config-path=/home/nonroot/configuration", 
      "--docker-compose-path=/home/nonroot/docker-compose.yml" ]
    ports:
      - "8081:8080"
    volumes:
      - "./dapr/components/:/home/nonroot/components"
      - "./dapr/configuration/:/home/nonroot/configuration"
      - ./docker-compose.yml:/home/nonroot/docker-compose.yml