services:
  # dapr sidecar
  actorsapi-1-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "--app-id", "actorsapi-1",
      "--app-port", "8080",
      "--log-level", "debug",
      "--placement-host-address", "dapr-placement:50006",
      "--scheduler-host-address", "dapr-scheduler:50007",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--resources-path", "./components",
      "--config", "/configuration/config.yaml",
      "--app-channel-address", "host.docker.internal"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    ports:
      - "3500:3500"
      - "50001:50001"