apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:
      - "apt update && apt install curl -y && sleep 604800"
  restartPolicy: Always

# apiVersion: v1
# kind: Pod
# metadata:
#   name: ubuntu
#   labels:
#     app: ubuntu
# spec:
#   containers:
#   - image: ubuntu
#     command:
#       - "sleep"
#       - "604800"
#     imagePullPolicy: IfNotPresent
#     name: ubuntu
#   restartPolicy: Always